// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: reward.proto

package reward

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Award struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Product       string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	PointCost     int64                  `protobuf:"varint,3,opt,name=point_cost,json=pointCost,proto3" json:"point_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Award) Reset() {
	*x = Award{}
	mi := &file_reward_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Award) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Award) ProtoMessage() {}

func (x *Award) ProtoReflect() protoreflect.Message {
	mi := &file_reward_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Award.ProtoReflect.Descriptor instead.
func (*Award) Descriptor() ([]byte, []int) {
	return file_reward_proto_rawDescGZIP(), []int{0}
}

func (x *Award) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Award) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Award) GetPointCost() int64 {
	if x != nil {
		return x.PointCost
	}
	return 0
}

type ListAwardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAwardsRequest) Reset() {
	*x = ListAwardsRequest{}
	mi := &file_reward_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAwardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAwardsRequest) ProtoMessage() {}

func (x *ListAwardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reward_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAwardsRequest.ProtoReflect.Descriptor instead.
func (*ListAwardsRequest) Descriptor() ([]byte, []int) {
	return file_reward_proto_rawDescGZIP(), []int{1}
}

type ListAwardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Awards        []*Award               `protobuf:"bytes,1,rep,name=awards,proto3" json:"awards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAwardsResponse) Reset() {
	*x = ListAwardsResponse{}
	mi := &file_reward_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAwardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAwardsResponse) ProtoMessage() {}

func (x *ListAwardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reward_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAwardsResponse.ProtoReflect.Descriptor instead.
func (*ListAwardsResponse) Descriptor() ([]byte, []int) {
	return file_reward_proto_rawDescGZIP(), []int{2}
}

func (x *ListAwardsResponse) GetAwards() []*Award {
	if x != nil {
		return x.Awards
	}
	return nil
}

type ClaimAwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AwardId       string                 `protobuf:"bytes,1,opt,name=award_id,json=awardId,proto3" json:"award_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimAwardRequest) Reset() {
	*x = ClaimAwardRequest{}
	mi := &file_reward_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimAwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimAwardRequest) ProtoMessage() {}

func (x *ClaimAwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reward_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimAwardRequest.ProtoReflect.Descriptor instead.
func (*ClaimAwardRequest) Descriptor() ([]byte, []int) {
	return file_reward_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimAwardRequest) GetAwardId() string {
	if x != nil {
		return x.AwardId
	}
	return ""
}

type ClaimAwardResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RemainingPoints int64                  `protobuf:"varint,2,opt,name=remaining_points,json=remainingPoints,proto3" json:"remaining_points,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClaimAwardResponse) Reset() {
	*x = ClaimAwardResponse{}
	mi := &file_reward_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimAwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimAwardResponse) ProtoMessage() {}

func (x *ClaimAwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reward_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimAwardResponse.ProtoReflect.Descriptor instead.
func (*ClaimAwardResponse) Descriptor() ([]byte, []int) {
	return file_reward_proto_rawDescGZIP(), []int{4}
}

func (x *ClaimAwardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClaimAwardResponse) GetRemainingPoints() int64 {
	if x != nil {
		return x.RemainingPoints
	}
	return 0
}

var File_reward_proto protoreflect.FileDescriptor

const file_reward_proto_rawDesc = "" +
	"\n" +
	"\freward.proto\x12\vquiz.reward\"P\n" +
	"\x05Award\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x1d\n" +
	"\n" +
	"point_cost\x18\x03 \x01(\x03R\tpointCost\"\x13\n" +
	"\x11ListAwardsRequest\"@\n" +
	"\x12ListAwardsResponse\x12*\n" +
	"\x06awards\x18\x01 \x03(\v2\x12.quiz.reward.AwardR\x06awards\".\n" +
	"\x11ClaimAwardRequest\x12\x19\n" +
	"\baward_id\x18\x01 \x01(\tR\aawardId\"Y\n" +
	"\x12ClaimAwardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x10remaining_points\x18\x02 \x01(\x03R\x0fremainingPoints2\xad\x01\n" +
	"\rRewardService\x12M\n" +
	"\n" +
	"ListAwards\x12\x1e.quiz.reward.ListAwardsRequest\x1a\x1f.quiz.reward.ListAwardsResponse\x12M\n" +
	"\n" +
	"ClaimAward\x12\x1e.quiz.reward.ClaimAwardRequest\x1a\x1f.quiz.reward.ClaimAwardResponseB?Z=github.com/rprajapati0067/quiz-game-backend/rpc/reward;rewardb\x06proto3"

var (
	file_reward_proto_rawDescOnce sync.Once
	file_reward_proto_rawDescData []byte
)

func file_reward_proto_rawDescGZIP() []byte {
	file_reward_proto_rawDescOnce.Do(func() {
		file_reward_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reward_proto_rawDesc), len(file_reward_proto_rawDesc)))
	})
	return file_reward_proto_rawDescData
}

var file_reward_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_reward_proto_goTypes = []any{
	(*Award)(nil),              // 0: quiz.reward.Award
	(*ListAwardsRequest)(nil),  // 1: quiz.reward.ListAwardsRequest
	(*ListAwardsResponse)(nil), // 2: quiz.reward.ListAwardsResponse
	(*ClaimAwardRequest)(nil),  // 3: quiz.reward.ClaimAwardRequest
	(*ClaimAwardResponse)(nil), // 4: quiz.reward.ClaimAwardResponse
}
var file_reward_proto_depIdxs = []int32{
	0, // 0: quiz.reward.ListAwardsResponse.awards:type_name -> quiz.reward.Award
	1, // 1: quiz.reward.RewardService.ListAwards:input_type -> quiz.reward.ListAwardsRequest
	3, // 2: quiz.reward.RewardService.ClaimAward:input_type -> quiz.reward.ClaimAwardRequest
	2, // 3: quiz.reward.RewardService.ListAwards:output_type -> quiz.reward.ListAwardsResponse
	4, // 4: quiz.reward.RewardService.ClaimAward:output_type -> quiz.reward.ClaimAwardResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reward_proto_init() }
func file_reward_proto_init() {
	if File_reward_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reward_proto_rawDesc), len(file_reward_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reward_proto_goTypes,
		DependencyIndexes: file_reward_proto_depIdxs,
		MessageInfos:      file_reward_proto_msgTypes,
	}.Build()
	File_reward_proto = out.File
	file_reward_proto_goTypes = nil
	file_reward_proto_depIdxs = nil
}
