// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: reward.proto

package reward

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RewardService_ListAwards_FullMethodName = "/quiz.reward.RewardService/ListAwards"
	RewardService_ClaimAward_FullMethodName = "/quiz.reward.RewardService/ClaimAward"
)

// RewardServiceClient is the client API for RewardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RewardServiceClient interface {
	ListAwards(ctx context.Context, in *ListAwardsRequest, opts ...grpc.CallOption) (*ListAwardsResponse, error)
	ClaimAward(ctx context.Context, in *ClaimAwardRequest, opts ...grpc.CallOption) (*ClaimAwardResponse, error)
}

type rewardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRewardServiceClient(cc grpc.ClientConnInterface) RewardServiceClient {
	return &rewardServiceClient{cc}
}

func (c *rewardServiceClient) ListAwards(ctx context.Context, in *ListAwardsRequest, opts ...grpc.CallOption) (*ListAwardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAwardsResponse)
	err := c.cc.Invoke(ctx, RewardService_ListAwards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rewardServiceClient) ClaimAward(ctx context.Context, in *ClaimAwardRequest, opts ...grpc.CallOption) (*ClaimAwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimAwardResponse)
	err := c.cc.Invoke(ctx, RewardService_ClaimAward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RewardServiceServer is the server API for RewardService service.
// All implementations must embed UnimplementedRewardServiceServer
// for forward compatibility.
type RewardServiceServer interface {
	ListAwards(context.Context, *ListAwardsRequest) (*ListAwardsResponse, error)
	ClaimAward(context.Context, *ClaimAwardRequest) (*ClaimAwardResponse, error)
	mustEmbedUnimplementedRewardServiceServer()
}

// UnimplementedRewardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRewardServiceServer struct{}

func (UnimplementedRewardServiceServer) ListAwards(context.Context, *ListAwardsRequest) (*ListAwardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAwards not implemented")
}
func (UnimplementedRewardServiceServer) ClaimAward(context.Context, *ClaimAwardRequest) (*ClaimAwardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimAward not implemented")
}
func (UnimplementedRewardServiceServer) mustEmbedUnimplementedRewardServiceServer() {}
func (UnimplementedRewardServiceServer) testEmbeddedByValue()                       {}

// UnsafeRewardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RewardServiceServer will
// result in compilation errors.
type UnsafeRewardServiceServer interface {
	mustEmbedUnimplementedRewardServiceServer()
}

func RegisterRewardServiceServer(s grpc.ServiceRegistrar, srv RewardServiceServer) {
	// If the following call pancis, it indicates UnimplementedRewardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RewardService_ServiceDesc, srv)
}

func _RewardService_ListAwards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAwardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RewardServiceServer).ListAwards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RewardService_ListAwards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RewardServiceServer).ListAwards(ctx, req.(*ListAwardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RewardService_ClaimAward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimAwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RewardServiceServer).ClaimAward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RewardService_ClaimAward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RewardServiceServer).ClaimAward(ctx, req.(*ClaimAwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RewardService_ServiceDesc is the grpc.ServiceDesc for RewardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RewardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quiz.reward.RewardService",
	HandlerType: (*RewardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAwards",
			Handler:    _RewardService_ListAwards_Handler,
		},
		{
			MethodName: "ClaimAward",
			Handler:    _RewardService_ClaimAward_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reward.proto",
}
